# Generated by Django 5.1.4 on 2026-09-11 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StratumDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('province', models.CharField(choices=[('HARARE', 'Harare'), ('BULAWAYO', 'Bulawayo'), ('MANICALAND', 'Manicaland'), ('MASHONALAND_CENTRAL', 'Mashonaland Central'), ('MASHONALAND_EAST', 'Mashonaland East'), ('MASHONALAND_WEST', 'Mashonaland West'), ('MASVINGO', 'Masvingo'), ('MATABELELAND_NORTH', 'Matabeleland North'), ('MATABELELAND_SOUTH', 'Matabeleland South'), ('MIDLANDS', 'Midlands')], max_length=32)),
                ('actor_family', models.CharField(choices=[('PRODUCER_FARMER', 'Producer / Farmer'), ('PROCESSOR', 'Processor'), ('AGGREGATOR_TRADER', 'Aggregator / Trader'), ('INPUT_SUPPLIER', 'Input Supplier'), ('FINANCIAL_SERVICE_PROVIDER', 'Financial Service Provider'), ('LOGISTICS_TRANSPORT', 'Logistics / Transport'), ('COOPERATIVE_FARMER_ORG', 'Cooperative / Farmer Organisation'), ('OTHER', 'Other')], max_length=32)),
                ('value_chain', models.CharField(choices=[('HORTICULTURE', 'Horticulture'), ('GRAIN_CEREALS', 'Grain / Cereals'), ('LIVESTOCK', 'Livestock'), ('DAIRY', 'Dairy'), ('POULTRY', 'Poultry'), ('OILSEEDS', 'Oilseeds'), ('COTTON', 'Cotton'), ('TOBACCO', 'Tobacco'), ('AQUACULTURE', 'Aquaculture'), ('OTHER', 'Other')], max_length=32)),
                ('size_class', models.CharField(choices=[('MICRO', 'Micro'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=16)),
                ('target_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('SOLE_TRADER', 'Sole Trader'), ('PARTNERSHIP', 'Partnership'), ('COOPERATIVE', 'Cooperative'), ('PRIVATE_LIMITED_COMPANY', 'Private Limited Company'), ('PUBLIC_COMPANY', 'Public Company'), ('TRUST', 'Trust'), ('OTHER', 'Other')], max_length=32)),
                ('province', models.CharField(choices=[('HARARE', 'Harare'), ('BULAWAYO', 'Bulawayo'), ('MANICALAND', 'Manicaland'), ('MASHONALAND_CENTRAL', 'Mashonaland Central'), ('MASHONALAND_EAST', 'Mashonaland East'), ('MASHONALAND_WEST', 'Mashonaland West'), ('MASVINGO', 'Masvingo'), ('MATABELELAND_NORTH', 'Matabeleland North'), ('MATABELELAND_SOUTH', 'Matabeleland South'), ('MIDLANDS', 'Midlands')], max_length=32)),
                ('district', models.CharField(max_length=128)),
                ('actor_family', models.CharField(choices=[('PRODUCER_FARMER', 'Producer / Farmer'), ('PROCESSOR', 'Processor'), ('AGGREGATOR_TRADER', 'Aggregator / Trader'), ('INPUT_SUPPLIER', 'Input Supplier'), ('FINANCIAL_SERVICE_PROVIDER', 'Financial Service Provider'), ('LOGISTICS_TRANSPORT', 'Logistics / Transport'), ('COOPERATIVE_FARMER_ORG', 'Cooperative / Farmer Organisation'), ('OTHER', 'Other')], max_length=32)),
                ('value_chain', models.CharField(choices=[('HORTICULTURE', 'Horticulture'), ('GRAIN_CEREALS', 'Grain / Cereals'), ('LIVESTOCK', 'Livestock'), ('DAIRY', 'Dairy'), ('POULTRY', 'Poultry'), ('OILSEEDS', 'Oilseeds'), ('COTTON', 'Cotton'), ('TOBACCO', 'Tobacco'), ('AQUACULTURE', 'Aquaculture'), ('OTHER', 'Other')], max_length=32)),
                ('size_class', models.CharField(choices=[('MICRO', 'Micro'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=16)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('UNREACHABLE', 'Unreachable'), ('DUPLICATE', 'Duplicate')], default='UNVERIFIED', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('sample_type', models.CharField(choices=[('MAIN', 'Main'), ('RESERVE', 'Reserve')], max_length=8)),
                ('status', models.CharField(max_length=16)),
                ('workflow_status', models.CharField(blank=True, choices=[('S00', 'Selected Main'), ('S01', 'Verification required'), ('S02', 'Organisation verified'), ('S03', 'Eligible respondent identified'), ('S04', 'Invitation prepared'), ('S05', 'Invitation sent'), ('S06', 'Invitation opened'), ('S07', 'Survey started'), ('S08', 'Survey submitted'), ('S09', 'QA query'), ('S10', 'QA passed'), ('S11', 'Completed'), ('S12', 'Refused'), ('S13', 'Nonresponse'), ('S14', 'Ineligible'), ('S15', 'Duplicate/inactive'), ('S16', 'Reserve eligible for activation')], max_length=8, null=True)),
                ('activation_reason', models.CharField(blank=True, choices=[('INELIGIBLE', 'Ineligible'), ('INACTIVE', 'Inactive'), ('DUPLICATE', 'Duplicate'), ('REFUSAL', 'Refusal'), ('NONRESPONSE_EXHAUSTED', 'Nonresponse exhausted')], max_length=32, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activation_evidence_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_reserves', to=settings.AUTH_USER_MODEL)),
                ('matched_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by', to='sampling.samplecase')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_cases', to='sampling.organisation')),
                ('stratum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_cases', to='sampling.stratumdefinition')),
            ],
        ),
    ]
