# Generated by Django 5.1.4 on 2026-09-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0004_stratumdefinition_unique_combo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stratumdefinition',
            name='unique_stratum_definition_combo',
        ),
        migrations.RemoveField(
            model_name='stratumdefinition',
            name='value_chain',
        ),
        migrations.AddField(
            model_name='organisation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='samplecase',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='actor_family',
            field=models.CharField(choices=[('AGGREGATION_MARKET_RETAIL', 'Aggregation / Market / Retail'), ('INPUTS_MECHANISATION', 'Inputs / Mechanisation'), ('PROCESSING_MANUFACTURING', 'Processing / Manufacturing'), ('PRODUCER_PRIMARY', 'Producer / Primary'), ('SERVICES_ENABLING', 'Services / Enabling'), ('FINANCE_INSURANCE', 'Finance / Insurance'), ('INSTITUTIONAL_COMMERCIAL_UNIT', 'Institutional Commercial Unit'), ('OTHER_VERIFY', 'Other / Verify')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='entity_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='size_class',
            field=models.CharField(choices=[('MICRO', 'Micro'), ('SME', 'SME'), ('UNKNOWN', 'Unknown'), ('LARGE_CORPORATE', 'Large / Corporate'), ('INSTITUTIONAL_OTHER', 'Institutional / Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='value_chain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stratumdefinition',
            name='actor_family',
            field=models.CharField(choices=[('AGGREGATION_MARKET_RETAIL', 'Aggregation / Market / Retail'), ('INPUTS_MECHANISATION', 'Inputs / Mechanisation'), ('PROCESSING_MANUFACTURING', 'Processing / Manufacturing'), ('PRODUCER_PRIMARY', 'Producer / Primary'), ('SERVICES_ENABLING', 'Services / Enabling'), ('FINANCE_INSURANCE', 'Finance / Insurance'), ('INSTITUTIONAL_COMMERCIAL_UNIT', 'Institutional Commercial Unit'), ('OTHER_VERIFY', 'Other / Verify')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stratumdefinition',
            name='size_class',
            field=models.CharField(choices=[('MICRO', 'Micro'), ('SME', 'SME'), ('UNKNOWN', 'Unknown'), ('LARGE_CORPORATE', 'Large / Corporate'), ('INSTITUTIONAL_OTHER', 'Institutional / Other')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='stratumdefinition',
            constraint=models.UniqueConstraint(fields=('province', 'actor_family', 'size_class'), name='unique_stratum_definition_combo'),
        ),
    ]
