# Generated by Django 5.1.4 on 2026-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0005_remove_stratumdefinition_unique_stratum_definition_combo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratumdefinition',
            name='code',
            field=models.CharField(max_length=96, unique=True),
        ),
    ]
