# Generated by Django 5.1.4 on 2026-09-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('manual_code_hash', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('ELIGIBILITY_PASSED', 'Eligibility passed'), ('CONSENTED', 'Consented'), ('SURVEY_STARTED', 'Survey started'), ('SUBMITTED', 'Submitted'), ('QA_PASSED', 'QA passed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='GENERATED', max_length=24)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PRINTED_CODE', 'Printed code'), ('QR', 'QR code')], max_length=16)),
                ('invitation_wave', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitation_tokens', to='sampling.samplecase')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
