# Generated by Django 5.1.4 on 2026-10-07 11:11

from django.db import migrations, models

import apps.invitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitationbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationbatch',
            name='channels',
            field=models.JSONField(default=apps.invitations.models.default_batch_channels),
        ),
    ]
