# Generated by Django 5.1.4 on 2026-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_batch_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationbatch',
            name='mode',
            field=models.CharField(default='INVITE', max_length=8),
        ),
    ]
