# Generated by Django 5.1.4 on 2026-09-11 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kii', '0001_initial'),
        ('sampling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('RA_ALLOWANCE', 'RA allowance'), ('AIRTIME_DATA', 'Airtime/data'), ('TRANSPORT', 'Transport'), ('ACCOMMODATION', 'Accommodation'), ('HOSTING', 'Hosting'), ('MESSAGING', 'Messaging'), ('OTHER', 'Other')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_costs', to=settings.AUTH_USER_MODEL)),
                ('kii_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_events', to='kii.kiirecord')),
                ('sample_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_events', to='sampling.samplecase')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
