# Generated by Django 5.1.4 on 2026-09-13 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_documentrecord_metadata_and_more'),
        ('kii', '0002_kiirecord_metadata_alter_kiirecord_preferred_mode_and_more'),
        ('kobo', '0003_reconciliationlog_error_message'),
        ('qa', '0002_seed_default_thresholds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qaevent',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_qa_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaevent',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qaevent',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qaevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_qa_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaevent',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed (not a real problem)')], default='OPEN', max_length=16),
        ),
        migrations.AddIndex(
            model_name='qaevent',
            index=models.Index(fields=['status', 'created_at'], name='qa_qaevent_status_82055b_idx'),
        ),
    ]
