# Generated by Django 5.1.4 on 2026-09-11 18:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consent', '0001_initial'),
        ('sampling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KIIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kii_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('stakeholder_category', models.CharField(max_length=64)),
                ('participant_name', models.CharField(max_length=255)),
                ('participant_role', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('NO_SHOW', 'No show')], default='INVITED', max_length=16)),
                ('preferred_mode', models.CharField(choices=[('TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('WHATSAPP_VOICE', 'WhatsApp voice'), ('WHATSAPP_VIDEO', 'WhatsApp video'), ('PHONE', 'Phone'), ('FACE_TO_FACE', 'Face to face')], max_length=16)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recording_reference', models.CharField(blank=True, max_length=512)),
                ('field_notes', models.TextField(blank=True)),
                ('transcript_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('VERIFIED', 'Verified'), ('ANONYMISED', 'Anonymised')], default='NOT_STARTED', max_length=16)),
                ('coding_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=16)),
                ('thematic_coverage_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_kiis', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kii_records', to='sampling.organisation')),
                ('participation_consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kii_participation_records', to='consent.consentrecord')),
                ('recording_consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kii_recording_records', to='consent.consentrecord')),
            ],
        ),
    ]
