# Generated by Django 5.1.4 on 2026-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiirecord',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='kiirecord',
            name='preferred_mode',
            field=models.CharField(blank=True, choices=[('TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('WHATSAPP_VOICE', 'WhatsApp voice'), ('WHATSAPP_VIDEO', 'WhatsApp video'), ('PHONE', 'Phone'), ('FACE_TO_FACE', 'Face to face')], max_length=16),
        ),
        migrations.AlterField(
            model_name='kiirecord',
            name='status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect (not yet contacted)'), ('INVITED', 'Invited'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('NO_SHOW', 'No show')], default='INVITED', max_length=16),
        ),
    ]
