# Generated by Django 5.1.4 on 2026-10-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kii', '0002_kiirecord_metadata_alter_kiirecord_preferred_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiirecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='kiirecord',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kiirecord',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='KIIInvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('manual_code_hash', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('CONSENTED', 'Consented'), ('STARTED', 'Started'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='GENERATED', max_length=16)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PRINTED_CODE', 'Printed code'), ('QR', 'QR code')], max_length=16)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kii_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitation_tokens', to='kii.kiirecord')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
