"""Loads document_tool_schema.json (generated by
manage.py build_document_tool_schema from the deployed XLSForm) once at
import time. Shared by ai_coding.py (the drafting prompt) and
kobo_submit.py (the submission XML builder) so both work from exactly the
same field list -- never two independently-typed copies of a 110-field
form drifting apart."""

import json
from pathlib import Path

SCHEMA_PATH = Path(__file__).resolve().parent / "document_tool_schema.json"
SCHEMA = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
