# Generated by Django 5.1.4 on 2026-10-07 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitationbatch'),
        ('kii', '0003_kiirecord_email_kiirecord_phone_and_more'),
        ('messaging', '0003_seed_dispatch_schedule'),
        ('sampling', '0006_alter_stratumdefinition_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=16)),
                ('purpose', models.CharField(choices=[('INVITATION', 'Invitation'), ('REMINDER', 'Reminder')], max_length=16)),
                ('provider_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('to_masked', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('UNDELIVERED', 'Not delivered'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=16)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('segments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_messages', to='invitations.invitationtoken')),
                ('kii_invitation_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_messages', to='kii.kiiinvitationtoken')),
                ('kii_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_messages', to='kii.kiirecord')),
                ('message_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_message', to='messaging.messagelog')),
                ('sample_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_messages', to='sampling.samplecase')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
