# Generated by Django 5.1.4 on 2026-10-07 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_finder_for_kii'),
        ('invitations', '0003_batch_channels'),
        ('messaging', '0005_sms_reminder_wording'),
        ('sampling', '0006_alter_stratumdefinition_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermessage',
            name='purpose',
            field=models.CharField(choices=[('INVITATION', 'Invitation'), ('REMINDER', 'Reminder'), ('INTRODUCTION', 'Introduction (ask first)'), ('REPLY', 'Reply in a conversation')], max_length=16),
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTRO_SENT', 'Asked'), ('REMINDED', 'Asked again'), ('ACCEPTED', 'Said yes: link sent'), ('DECLINED', 'Said no'), ('NO_REPLY', 'No reply'), ('NOT_DELIVERED', 'Could not be delivered')], default='INTRO_SENT', max_length=16)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=16)),
                ('number_hash', models.CharField(db_index=True, max_length=64)),
                ('number_masked', models.CharField(max_length=32)),
                ('intro_sent_at', models.DateTimeField()),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('sms_fallback_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invitation_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invitations.invitationtoken')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.respondent')),
                ('sample_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='sampling.samplecase')),
            ],
            options={
                'ordering': ['-intro_sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_sid', models.CharField(max_length=64, unique=True)),
                ('number_hash', models.CharField(db_index=True, max_length=64)),
                ('from_masked', models.CharField(max_length=32)),
                ('from_number', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('OTHER', 'Other')], default='OTHER', max_length=8)),
                ('auto_reply', models.TextField(blank=True)),
                ('needs_person', models.BooleanField(default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='sampling.samplecase')),
                ('outreach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.outreach')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
