# Generated by Django 5.1.4 on 2026-09-11 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kii', '0001_initial'),
        ('sampling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('mode', models.CharField(choices=[('TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('WHATSAPP_VOICE', 'WhatsApp voice'), ('WHATSAPP_VIDEO', 'WhatsApp video'), ('PHONE', 'Phone'), ('FACE_TO_FACE', 'Face to face')], max_length=16)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kii_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='kii.kiirecord')),
                ('sample_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='sampling.samplecase')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('SMS', 'SMS'), ('FACE_TO_FACE', 'Face to face')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('REACHED', 'Reached'), ('NO_ANSWER', 'No answer'), ('WRONG_NUMBER', 'Wrong number'), ('REFUSED', 'Refused'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_events', to=settings.AUTH_USER_MODEL)),
                ('sample_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_events', to='sampling.samplecase')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role_category', models.CharField(choices=[('OWNER_FOUNDER', 'Owner/founder'), ('CEO_MD', 'CEO/MD'), ('FINANCE_CREDIT_RISK', 'Finance/credit/risk'), ('OPERATIONS', 'Operations'), ('STRATEGY_BD', 'Strategy/BD'), ('SUPPLY_CHAIN_COMMERCIAL', 'Supply chain/commercial'), ('OTHER_SENIOR_MANAGER', 'Other senior manager')], max_length=32)),
                ('is_eligible', models.BooleanField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('whatsapp_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gatekeeper_name', models.CharField(blank=True, max_length=255)),
                ('gatekeeper_contact', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligibility_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_checks', to=settings.AUTH_USER_MODEL)),
                ('sample_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondents', to='sampling.samplecase')),
            ],
        ),
    ]
