# Generated by Django 5.1.4 on 2026-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='role_category',
            field=models.CharField(blank=True, choices=[('OWNER_FOUNDER', 'Owner/founder'), ('CEO_MD', 'CEO/MD'), ('FINANCE_CREDIT_RISK', 'Finance/credit/risk'), ('OPERATIONS', 'Operations'), ('STRATEGY_BD', 'Strategy/BD'), ('SUPPLY_CHAIN_COMMERCIAL', 'Supply chain/commercial'), ('OTHER_SENIOR_MANAGER', 'Other senior manager')], max_length=32),
        ),
    ]
