# Generated by Django 5.1.4 on 2026-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_respondent_role_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
