# Generated by Django 5.1.4 on 2026-10-03 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_respondent_phone_and_more'),
        ('sampling', '0006_alter_stratumdefinition_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='RUNNING', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=16)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('searches_used', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('dropped', models.JSONField(blank=True, default=list)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_searches', to='sampling.samplecase')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ORG_PHONE', 'Organisation phone'), ('ORG_EMAIL', 'Organisation email'), ('WEBSITE', 'Website'), ('OFFICE_LOCATION', 'Office location'), ('PERSON', 'Senior staff member')], max_length=16)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('person_name', models.CharField(blank=True, max_length=255)),
                ('person_title', models.CharField(blank=True, max_length=255)),
                ('person_email', models.EmailField(blank=True, max_length=254)),
                ('person_phone', models.CharField(blank=True, max_length=64)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(blank=True, max_length=16)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=8)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_proposals', to='contacts.respondent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_proposals', to='sampling.samplecase')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='contacts.contactsearchrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
