# Generated by Django 5.1.4 on 2026-10-04 10:28

from django.db import migrations, models


def mark_waiting_runs_queued(apps, schema_editor):
    """Before this migration a run said RUNNING from the moment it was requested, so a batch of 50 showed 50
    "running" searches while the single worker did them one at a time. Unfinished runs are really waiting: mark them
    QUEUED (the worker sets RUNNING when it starts one) and group them so the register can show their progress."""
    Run = apps.get_model("contacts", "ContactSearchRun")
    Run.objects.filter(status="RUNNING", finished_at__isnull=True).update(status="QUEUED", batch="queued-before-research-lane")


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactsearchrun_contactproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsearchrun',
            name='batch',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name='contactsearchrun',
            name='running_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactsearchrun',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='QUEUED', max_length=8),
        ),
        migrations.RunPython(mark_waiting_runs_queued, migrations.RunPython.noop),
    ]
