# Generated by Django 5.1.4 on 2026-10-04 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_search_queue'),
        ('kii', '0003_kiirecord_email_kiirecord_phone_and_more'),
        ('sampling', '0006_alter_stratumdefinition_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactproposal',
            name='kii_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_proposals', to='kii.kiirecord'),
        ),
        migrations.AddField(
            model_name='contactsearchrun',
            name='kii_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_searches', to='kii.kiirecord'),
        ),
        migrations.AlterField(
            model_name='contactproposal',
            name='sample_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_proposals', to='sampling.samplecase'),
        ),
        migrations.AlterField(
            model_name='contactsearchrun',
            name='sample_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_searches', to='sampling.samplecase'),
        ),
        migrations.AddConstraint(
            model_name='contactproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kii_record__isnull', True), ('sample_case__isnull', False)), models.Q(('kii_record__isnull', False), ('sample_case__isnull', True)), _connector='OR'), name='contact_proposal_one_target'),
        ),
        migrations.AddConstraint(
            model_name='contactsearchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kii_record__isnull', True), ('sample_case__isnull', False)), models.Q(('kii_record__isnull', False), ('sample_case__isnull', True)), _connector='OR'), name='contact_search_one_target'),
        ),
    ]
