# Generated by Django 5.1.4 on 2026-09-11 18:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kii', '0001_initial'),
        ('kobo', '0002_seed_reconciliation_schedule'),
        ('sampling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('author_or_speaker', models.CharField(blank=True, max_length=255)),
                ('publication_or_event_date', models.DateField(blank=True, null=True)),
                ('source_url_or_reference', models.CharField(blank=True, max_length=1024)),
                ('document_type', models.CharField(choices=[('OFFICIAL', 'Official'), ('SECONDARY', 'Secondary'), ('PLATFORM', 'Platform')], max_length=16)),
                ('authenticity_assessment', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed')], default='UNVERIFIED', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('geographic_scope', models.CharField(blank=True, max_length=255)),
                ('value_chain', models.CharField(blank=True, max_length=32)),
                ('construct_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('evidence_extract', models.TextField(blank=True)),
                ('interpretive_memo', models.TextField(blank=True)),
                ('qa_status', models.CharField(choices=[('PENDING', 'Pending'), ('INCLUDED', 'Included'), ('EXCLUDED', 'Excluded')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='sampling.organisation')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('triangulation_kii_records', models.ManyToManyField(blank=True, related_name='triangulated_documents', to='kii.kiirecord')),
                ('triangulation_quan_submissions', models.ManyToManyField(blank=True, related_name='triangulated_documents', to='kobo.quansubmission')),
            ],
        ),
    ]
