# Generated by Django 5.1.4 on 2026-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='documentrecord',
            name='value_chain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
