# Generated by Django 5.1.4 on 2026-09-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_documentrecord_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='source_file_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='source_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='source_file_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='source_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='source_file_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
