# Generated by Django 5.1.4 on 2026-09-17 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_documentrecord_source_file_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='ai_draft',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='ai_draft_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='ai_draft_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='kobo_submission_uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='kobo_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='kobo_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
