# Generated by Django 5.1.4 on 2026-09-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_documentrecord_ai_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='ai_draft_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='ai_draft_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='ai_draft_status',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
