# Generated by Django 5.1.4 on 2026-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_documentrecord_ai_draft_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='ai_draft_progress',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
