# Generated by Django 5.1.4 on 2026-09-12 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kii', '0002_kiirecord_metadata_alter_kiirecord_preferred_mode_and_more'),
        ('sampling', '0006_alter_stratumdefinition_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_intro_ack', models.BooleanField(default=False)),
                ('permission_to_use_correction', models.BooleanField(blank=True, null=True)),
                ('verification_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('background_questions_avoided', models.PositiveIntegerField(default=0)),
                ('burden_reduction_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('known_evidence_summary', models.TextField(blank=True)),
                ('unresolved_gaps', models.TextField(blank=True)),
                ('contradictions', models.TextField(blank=True)),
                ('priority_probe_questions', models.TextField(blank=True)),
                ('role_specific_module', models.CharField(blank=True, max_length=64)),
                ('executive_short_form', models.BooleanField(default=False)),
                ('researcher_reviewed', models.BooleanField(default=False)),
                ('prepopulation_locked_at', models.DateTimeField(blank=True, null=True)),
                ('interview_completed_at', models.DateTimeField(blank=True, null=True)),
                ('reconciliation_status', models.CharField(choices=[('PENDING', 'Pending'), ('RECONCILED', 'Reconciled'), ('UNRESOLVED', 'Unresolved')], default='PENDING', max_length=16)),
                ('protocol_deviation', models.BooleanField(default=False)),
                ('deviation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kii_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_profiles', to='kii.kiirecord')),
                ('qa_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proit_qa_reviews', to=settings.AUTH_USER_MODEL)),
                ('sample_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_profiles', to='sampling.samplecase')),
            ],
        ),
        migrations.CreateModel(
            name='PreProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=64)),
                ('module', models.CharField(choices=[('CASE_CONTROL', 'A. Case Control & Routing'), ('RESPONDENT_PROFILE', 'B. Respondent Professional Profile'), ('ORGANISATION_PROFILE', 'C. Organisation Profile'), ('OPERATIONS_MARKETS', 'D. Operations & Markets'), ('FINANCE_CONTEXT', 'E. Public Finance/Bankability Context'), ('INSTITUTIONAL_DIGITAL', 'F. Institutional & Digital Context')], max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('route', models.CharField(choices=[('QUAN', 'QUAN only'), ('KII', 'KII only'), ('BOTH', 'Both QUAN and KII')], default='BOTH', max_length=8)),
                ('preliminary_documentary_value', models.TextField(blank=True)),
                ('respondent_value', models.TextField(blank=True)),
                ('reconciled_value', models.TextField(blank=True)),
                ('confidence', models.CharField(blank=True, choices=[('HIGH', 'High -- authoritative or two concordant sources'), ('MODERATE', 'Moderate -- one credible source, or minor staleness'), ('LOW', 'Low -- weak/old/ambiguous/uncorroborated')], max_length=16)),
                ('gap_classification', models.CharField(blank=True, choices=[('VERIFY_ONLY', 'Verify only'), ('VERIFY_AND_PROBE', 'Verify and probe'), ('ASK_FULL', 'Ask full'), ('SKIP_BACKGROUND_ONLY', 'Skip (background only)')], max_length=24)),
                ('verification_status', models.CharField(blank=True, choices=[('YES_CORRECT', 'Respondent confirms preliminary value'), ('NO_CORRECT_VALUE_PROVIDED', 'Respondent rejects and supplies corrected value'), ('PARTLY_CORRECT', 'Respondent qualifies or updates the value'), ('DO_NOT_KNOW', 'Respondent cannot verify'), ('PREFER_NOT_TO_SAY', 'Respondent declines'), ('NOT_APPLICABLE', 'Field does not apply')], max_length=32)),
                ('verification_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pre_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='proit.preprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('source_title', models.CharField(max_length=512)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('access_date', models.DateField(blank=True, null=True)),
                ('locator', models.CharField(blank=True, max_length=1024)),
                ('source_authority', models.CharField(blank=True, choices=[('TIER_1_STATUTORY', 'Tier 1 -- statutory/official register or audited report'), ('TIER_2_INSTITUTIONAL', 'Tier 2 -- official website, investor report, association record'), ('TIER_3_MEDIA', 'Tier 3 -- reputable media, conference bio, professional profile'), ('TIER_4_SOCIAL', 'Tier 4 -- corroborated public social/platform content')], max_length=24)),
                ('source_confidence', models.CharField(choices=[('HIGH', 'High -- authoritative or two concordant sources'), ('MODERATE', 'Moderate -- one credible source, or minor staleness'), ('LOW', 'Low -- weak/old/ambiguous/uncorroborated')], max_length=16)),
                ('source_conflict', models.BooleanField(default=False)),
                ('researcher_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proit_evidence_added', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='proit.preprofilefield')),
            ],
        ),
        migrations.AddConstraint(
            model_name='preprofilefield',
            constraint=models.UniqueConstraint(fields=('pre_profile', 'field_id'), name='unique_pre_profile_field'),
        ),
    ]
