# Generated by Django 5.1.4 on 2026-09-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprofilefield',
            options={'ordering': ['id']},
        ),
    ]
