# Generated by Django 5.1.4 on 2026-09-21 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proit', '0002_pre_profile_field_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='RUNNING', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('searches_used', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('dropped', models.JSONField(blank=True, default=list)),
                ('pre_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='proit.preprofile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('NOT_FOUND', 'Not found publicly'), ('ACCEPTED', 'Accepted'), ('EDITED', 'Accepted with edits'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=10)),
                ('proposed_value', models.TextField(blank=True)),
                ('final_value', models.TextField(blank=True)),
                ('confidence', models.CharField(blank=True, choices=[('HIGH', 'High -- authoritative or two concordant sources'), ('MODERATE', 'Moderate -- one credible source, or minor staleness'), ('LOW', 'Low -- weak/old/ambiguous/uncorroborated')], max_length=16)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pre_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to='proit.preprofile')),
                ('profile_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_proposals', to='proit.preprofilefield')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='proit.airesearchrun')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'field_id'), name='unique_ai_proposal_per_run_field')],
            },
        ),
    ]
