# Generated by Django 5.1.4 on 2026-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proit', '0003_ai_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprofile',
            name='kobo_submission_uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='preprofile',
            name='kobo_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
