# Generated by Django 5.1.4 on 2026-09-11 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sampling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_started_at', models.DateTimeField()),
                ('run_finished_at', models.DateTimeField(blank=True, null=True)),
                ('submissions_pulled', models.PositiveIntegerField(default=0)),
                ('new_submissions', models.PositiveIntegerField(default=0)),
                ('updated_submissions', models.PositiveIntegerField(default=0)),
                ('mismatches_flagged', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(choices=[('SCHEDULE', 'Schedule'), ('WEBHOOK_HEADSUP', 'Webhook heads-up'), ('MANUAL', 'Manual')], max_length=16)),
            ],
            options={
                'ordering': ['-run_started_at'],
            },
        ),
        migrations.CreateModel(
            name='QUANSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_submission_uuid', models.CharField(max_length=64, unique=True)),
                ('administration_mode', models.CharField(choices=[('01', 'Web self-administration'), ('02', 'WhatsApp link, self-completion'), ('03', 'Telephone interviewer-administered'), ('04', 'WhatsApp call, interviewer-assisted'), ('05', 'Video call, interviewer-assisted'), ('06', 'Face to face')], max_length=2)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('completion_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('qa_status', models.CharField(choices=[('PENDING', 'Pending'), ('QUERY', 'Query'), ('QA_PASSED', 'QA passed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('raw_payload_ref', models.CharField(blank=True, max_length=255)),
                ('payload_content_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_submissions', to=settings.AUTH_USER_MODEL)),
                ('sample_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quan_submissions', to='sampling.samplecase')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
