# Generated by Django 5.1.4 on 2026-09-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0002_seed_reconciliation_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
