# Generated by Django 5.1.4 on 2026-09-15 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0003_reconciliationlog_error_message'),
        ('sampling', '0006_alter_stratumdefinition_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quansubmission',
            index=models.Index(fields=['-submitted_at'], name='quan_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='quansubmission',
            index=models.Index(fields=['qa_status', 'submitted_at'], name='quan_qa_queue_idx'),
        ),
    ]
