# Generated by Django 5.1.4 on 2026-09-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0004_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(max_length=20)),
                ('run_started_at', models.DateTimeField()),
                ('run_finished_at', models.DateTimeField(blank=True, null=True)),
                ('pulled', models.PositiveIntegerField(default=0)),
                ('new', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('removed', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(choices=[('SCHEDULE', 'Schedule'), ('WEBHOOK_HEADSUP', 'Webhook heads-up'), ('MANUAL', 'Manual')], max_length=16)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-run_started_at'],
                'indexes': [models.Index(fields=['form_key', '-run_started_at'], name='kobo_formsync_idx')],
            },
        ),
        migrations.CreateModel(
            name='KoboFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(max_length=20)),
                ('kobo_id', models.BigIntegerField()),
                ('kobo_uuid', models.CharField(blank=True, max_length=64)),
                ('record', models.CharField(blank=True, max_length=120)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('first_synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField()),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at', '-kobo_id'],
                'indexes': [models.Index(fields=['form_key', 'record'], name='kobo_formsub_record_idx')],
                'constraints': [models.UniqueConstraint(fields=('form_key', 'kobo_id'), name='kobo_form_submission_unique')],
            },
        ),
    ]
