# Generated by Django 5.1.4 on 2026-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('PARTICIPATION', 'Participation'), ('KII_RECORDING', 'KII recording')], max_length=16)),
                ('information_sheet_version', models.CharField(max_length=32)),
                ('decision', models.CharField(choices=[('GIVEN', 'Given'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], max_length=16)),
                ('method', models.CharField(choices=[('WEB_CLICKTHROUGH', 'Web click-through'), ('VERBAL_RA_RECORDED', 'Verbal, RA-recorded'), ('WRITTEN', 'Written')], max_length=24)),
                ('timestamp', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
