# Generated by Django 5.1.4 on 2026-09-11 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consent', '0001_initial'),
        ('contacts', '0001_initial'),
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='contacts.respondent'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='sample_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='sampling.samplecase'),
        ),
    ]
