# Generated by Django 5.1.4 on 2026-09-11 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_initial'),
        ('kii', '0001_initial'),
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='kii_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='kii.kiirecord'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='sample_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='sampling.samplecase'),
        ),
    ]
