# Generated by Django 5.1.4 on 2026-09-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0003_consentrecord_kii_record_and_more'),
        ('contacts', '0003_alter_respondent_phone_and_more'),
        ('kii', '0002_kiirecord_metadata_alter_kiirecord_preferred_mode_and_more'),
        ('sampling', '0006_alter_stratumdefinition_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['sample_case', 'consent_type', '-timestamp'], name='consent_latest_idx'),
        ),
    ]
